use Ritualia;

INSERT INTO songs (title, artist, source_id, explication_source) VALUES
("Dias de Luta, Dias de Glória", "Charlie Brown Jr.", "6eEOegzrwJg", "explication_audios/dias_de_luta_dias_de_gloria.mp3"),
("Tempo Perdido", "Legião Urbana", "LqmRIG1plVU", "explication_audios/tempo_perdido.mp3"),
("Por Você", "Barão Vermelho", "JhwJ7_h0i-M", "explication_audios/por_voce.mp3"),
("Andar com Fé", "Gilberto Gil", "kyy4SqIw-EY", "explication_audios/andar_com_fe.mp3"),
("Cálice", "Chico Buarque & Gilberto Gil", "9y2xB90A0CY", "explication_audios/calice.mp3"),
("Oceano", "Djavan", "P-lxOj0XpEE", "explication_audios/oceano.mp3"),
("Amanhã Sei Lá", "Marcos & Belutti", "tu5bpM3CcUw", "explication_audios/amanha_sei_la.mp3"),
("Romaria", "Renato Teixeira", "OYCS6SJtHvI", "explication_audios/romaria.mp3"),
("Evidências", "Chitãozinho & Xororó", "ePjtnSPFWK8", "explication_audios/evidencias.mp3"),
("Apesar de Você", "Chico Buarque", "bGAJlOwUgHY", "explication_audios/apesar_de_voce.wav"),
("Alegria, Alegria", "Caetano Veloso", "he_ghOAXbSM", "explication_audios/alegria_alegria.wav"),
("Aquele Abraço", "Gilberto Gil", "zFGMLQ3q15c", "explication_audios/aquele_abraco.wav"),
("O Bêbado e a Equilibrista", "Elis Regina", "oCcREJdgRXM", "explication_audios/o_bebado_e_a_equilibrista.wav"),
("Coração de Estudante", "Milton Nascimento", "pI734oE7iUw", "explication_audios/coracao_de_estudante.wav"),
("Blowin’ in the Wind", "Bob Dylan", "MMFj8uDubsE", "explication_audios/blowin_in_the_wind.wav"),
("We Shall Overcome", "Joan Baez", "nM39QUiAsoM", "explication_audios/we_shall_overcome.wav"),
("The Sound of Silence", "Simon & Garfunkel", "NAEppFUWLfc", "explication_audios/the_sound_of_silence.wav"),
("Feeling Good", "Nina Simone", "oHRNrgDIJfo", "explication_audios/feeling_good.wav"),
("Imagine", "John Lennon", "VOgFZfRVaww", "explication_audios/imagine.wav"),
("Epitáfio", "Titãs", "cvznde5nc_s", "explication_audios/epitafio.wav"),
("Sociedade Alternativa", "Raul Seixas", "CfgYcLBP9lI", "explication_audios/sociedade_alternativa.wav"),
("Alagados", "Os Paralamas do Sucesso", "r6esToXGQJM", "explication_audios/alagados.wav"),
("Pro Dia Nascer Feliz", "Barão Vermelho", "sQzT4VObtZs", "explication_audios/pro_dia_nascer_feliz.wav"),
("Hey Jude", "The Beatles", "A_MjCqQoLLA", "explication_audios/hey_jude.wav"),
("We Will Rock You", "Queen", "-tJYN-eG1zk", "explication_audios/we_will_rock_you.wav"),
("Sunday Bloody Sunday", "U2", "Iqlzoz_jH3c", "explication_audios/sunday_bloody_sunday.wav"),
("Another Brick in the Wall", "Pink Floyd", "qs35t2xFqdU", "explication_audios/another_brick_in_the_wall.wav"),
("Smells Like Teen Spirit", "Nirvana", "hTWKbfoikeg", "explication_audios/smells_like_teen_spirit.wav"),
("As Rosas Não Falam", "Cartola", "5j3QjEk-6c0", "explication_audios/as_rosas_nao_falam.wav"),
("Com Que Roupa?", "Noel Rosa", "CUo6DLq_F0E", "explication_audios/com_que_roupa.wav"),
("O Mar Serenou", "Clara Nunes", "drGewMyo00A", "explication_audios/o_mar_serenou.wav"),
("Canta, Canta Minha Gente", "Martinho da Vila", "X4Tp_TmjHRs", "explication_audios/canta_canta_minha_gente.wav"),
("Foi um Rio que Passou em Minha Vida", "Paulinho da Viola", "DFBBy0RY8p0", "explication_audios/foi_um_rio_que_passou_em_minha_vida.wav"),
("Sodade", "Cesária Évora", "ku_WZoTtT8Q", "explication_audios/sodade.wav"),
("Pata Pata", "Miriam Makeba", "JBJVVhn7iuo", "explication_audios/pata_pata.wav"),
("Chan Chan", "Buena Vista Social Club", "tGbRZ73NvlY", "explication_audios/chan_chan.wav"),
("Clandestino", "Manu Chao", "TyA-oz7lSrc", "explication_audios/clandestino.wav"),
("7 Seconds", "Youssou NDour & Neneh Cherry", "wqCpjFMvz-k", "explication_audios/7_seconds.wav"),
("Festa", "Ivete Sangalo", "h2xU3E6kePw", "explication_audios/festa.wav"),
("Show das Poderosas", "Anitta", "FGViL3CYRwg", "explication_audios/show_das_poderosas.wav"),
("Ainda Bem", "Marisa Monte", "Pmt01TGsGGA", "explication_audios/ainda_bem.wav"),
("Quando Você Passa (Turu Turu)", "Sandy & Junior", "tCvLOhusfwM", "explication_audios/quando_voce_passa_turu_turu.wav"),
("Heal the World", "Michael Jackson", "BWf-eARnf6U", "explication_audios/heal_the_world.wav"),
("Halo", "Beyoncé", "bnVUHWCynig", "explication_audios/halo.wav"),
("Viva La Vida", "Coldplay", "dvgZkm1xWPE", "explication_audios/viva_la_vida.wav"),
("Someone Like You", "Adele", "hLQl3WQQoQ0", "explication_audios/someone_like_you.wav"),
("Shape of You", "Ed Sheeran", "JGwWNGJdvx8", "explication_audios/shape_of_you.wav"),
("Bachianas Brasileiras nº 5", "Heitor Villa||Lobos", "pUCuEd1tjCg", "explication_audios/bachianas_brasileiras_no_5.wav"),
("Odeon", "Ernesto Nazareth", "bEfRtR12Y4k", "explication_audios/odeon.wav"),
("Garota de Ipanema", "Tom Jobim & Vinicius de Moraes", "KJzBxJ8ExRk", "explication_audios/garota_de_ipanema.wav"),
("Ode to Joy", "Ludwig van Beethoven", "-kcOpyM9cBg", "explication_audios/ode_to_joy.wav"),
("Eine Kleine Nachtmusik", "Wolfgang Amadeus Mozart", "oy2zDJPIgwc", "explication_audios/eine_kleine_nachtmusik.wav"),
("What a Wonderful World", "Louis Armstrong", "rBrd_3VMC3c", "explication_audios/what_a_wonderful_world.wav"),
("Billie Jean", "Michael Jackson", "Zi_XLOBDo_Y", "explication_audios/billie_jean.wav"),
("Like a Prayer", "Madonna", "79fzeNUqQbQ", "explication_audios/like_a_prayer.wav"),
("Born This Way", "Lady Gaga", "wV1FrqwZyKw", "explication_audios/born_this_way.wav"),
("Levitating", "Dua Lipa", "TUVcZfQe-Kw", "explication_audios/levitating.wav"),
("Bohemian Rhapsody", "Queen", "fJ9rUzIMcZQ", "explication_audios/bohemian_rhapsody.wav"),
("Satisfaction", "The Rolling Stones", "nrIPxlFzDi0", "explication_audios/satisfaction.wav");

INSERT INTO genres (name, path) VALUES
("MPB", "genres/mpb.png"),
("Sertanejo", "genres/sertanejo.png"),
("Rock", "genres/rock.png"),
("Tropicalismo", "genres/tropicalismo.png"),
("Folk", "genres/folk.png"),
("Folk Rock", "genres/folk_rock.png"),
("Jazz", "genres/jazz.png"),
("Pop Rock", "genres/pop_rock.png"),
("Rock Nacional", "genres/rock_nacional.png"),
("Rock Progressivo", "genres/rock_progressivo.png"),
("Grunge", "genres/grunge.png"),
("Samba", "genres/samba.png"),
("Morna", "genres/morna.png"),
("Afropop", "genres/afropop.png"),
("Son Cubano", "genres/son_cubano.png"),
("World Music", "genres/world_music.png"),
("Axé", "genres/axe.png"),
("Funk Pop", "genres/funk_pop.png"),
("Pop", "genres/pop.png"),
("Música Clássica", "genres/musica_classica.png"),
("Choro", "genres/choro.png"),
("Bossa Nova", "genres/bossa_nova.png");

INSERT INTO emotions (name) VALUES
("Esperança"),
("Reflexão"),
("Saudade"),
("Liberdade"),
("Otimismo"),
("Melancolia"),
("Unidade"),
("Introspecção"),
("Empoderamento"),
("Paz"),
("Rebeldia"),
("Indignação"),
("Euforia"),
("Acolhimento"),
("Empolgação"),
("Tensão"),
("Revolta"),
("Raiva"),
("Ironia"),
("Devoção"),
("Alegria"),
("Nostalgia"),
("Animação"),
("Inquietude"),
("Empatia"),
("Serenidade"),
("Romantismo"),
("Compaixão"),
("Paixão"),
("Triunfo"),
("Tristeza"),
("Sensualidade"),
("Elegância"),
("Leveza"),
("Júbilo"),
("Gratidão"),
("Êxtase"),
("Orgulho"),
("Drama"),
("Frustração");

INSERT INTO songs_genres (song_id, genre_id) VALUES
(38, 16),
(41, 1),
(22, 8),
(11, 4),
(7, 2),
(4, 1),
(27, 3),
(10, 1),
(12, 12),
(29, 12),
(48, 21),
(54, 20),
(15, 5),
(58, 10),
(56, 20),
(5, 1),
(32, 12),
(36, 15),
(37, 17),
(30, 22),
(14, 1),
(1, 9),
(52, 21),
(20, 9),
(9, 2),
(18, 7),
(39, 18),
(33, 12),
(50, 22),
(44, 20),
(43, 20),
(24, 20),
(19, 20),
(57, 20),
(55, 20),
(13, 1),
(31, 12),
(6, 1),
(51, 21),
(49, 22),
(35, 14),
(3, 9),
(23, 9),
(42, 20),
(8, 2),
(59, 3),
(47, 20),
(40, 19),
(28, 11),
(21, 9),
(34, 13),
(46, 20),
(26, 3),
(2, 9),
(17, 6),
(45, 20),
(16, 5),
(25, 3),
(53, 7);

INSERT INTO songs_emotions (song_id, emotion_id) VALUES
(1, 5),
(2, 2),
(3, 27),
(4, 5),
(5, 12),
(6, 29),
(7, 34),
(8, 20),
(9, 39),
(10, 1),
(11, 4),
(12, 36),
(13, 1),
(14, 7),
(15, 2),
(16, 7),
(17, 8),
(18, 9),
(19, 10),
(20, 2),
(21, 11),
(22, 12),
(23, 15),
(24, 14),
(25, 30),
(26, 17),
(27, 11),
(28, 18),
(29, 6),
(30, 19),
(31, 26),
(32, 21),
(33, 38),
(34, 3),
(35, 23),
(36, 22),
(37, 25),
(38, 28),
(39, 13),
(40, 9),
(41, 36),
(42, 29),
(43, 28),
(44, 20),
(45, 39),
(46, 31),
(47, 32),
(48, 33),
(49, 33),
(50, 34),
(51, 35),
(52, 34),
(53, 36),
(54, 16),
(55, 37),
(56, 9),
(57, 23),
(58, 39),
(59, 40);


INSERT INTO national_teams(name, anthem_source_id, explication_audios) VALUES
("brasil", "Z7pFwsX6UVc", "Brasil_nsuay7.wav"),
("canada", "RidIw0OXs9U", "Canada_sbu0lv.wav"),
("colômbia", "yPSL78YDyZY", "Colombia_ysfnsi.wav"),
("Espanha", "BsWFAEytD24", "Espanha_rg4xxk.wav"),
("franca", "YLi5A7BiBVk", "Franca_cstqjd.wav"),
("Inglaterra", "xianOAFljbs", "Inglaterra_ntug23.wav"),
("Japão", "tkXDCs8qX8Y", "Japao_rxyuwe.wav"),
("mexico", "oZkTymsI7eI", "M%C3%A9xico_sw1kiv.wav"),
("portugal", "DdOEpfypWQA", "Portugal_nmuuhx.wav"),
("usa", "LroNerBwIV4", "EUA_supfbt.wav"),
("argentina", "2zJ8UsfLa9I", "Argentina_zyowxx.wav"),
("alemanha", "-k07t4WsXtU", "Alemanha_za09q8.wav"),
("holanda", "S1J1St_rU90", "Holanda_c6orvm.wav");

INSERT INTO brazilian_songs(name, source_id, explication_audios) VALUES
("A Taça do Mundo É Nossa", "hJAriHOh1Jg", "A_Ta%C3%A7a_do_Mundo_%C3%89_Nossa_pznbtz.wav"),
("Frevo do Bi", "6z1jZ0oq7mo", "Frevo_do_Bi_gnmx74.wav"),
("Pra Frente Brasil", "LbxtNtGlZxE", "Para_a_Frente_Brasil_mgzbhb.wav"),
("Voa Canarinho Voa", "FSelnob-HIs", "Voa_Canarinho_Voa_rw8ia1.wav"),
("Coração Verde e Amarelo", "vghnSY7IdJg", "Cora%C3%A7%C3%A3o_Verde_e_Amarelo_ryc65o.wav"),
("La La La (Brasil 2014)", "-befR4wHsjQ", "La_La_La_Brasil_2014_ttzie9.wav"),
("Mostra tua força", "VasURheNUOM", "Mostra_tua_for%C3%A7a_pcct0p.wav"),
("Hino do Penta", "SS14L3soacs", "Hino_do_Penta_utngee.wav"),
("País do Futebol", "801gN8_X39E", "Pa%C3%ADs_do_Futebol_m966ox.wav"),
("A Escola de Feola", "MELfSGXA9Ds", "Escola_de_Feola_dprgvv.wav"),
("Waka waka", "pRpeEdMmmQ0", "Waka_waka_ok7qg7.wav"),
("Você chegou", "0NXEDQqILUE", "Voc%C3%AA_chegou_b0had0.wav"),
("Juntos Num Só Ritmo", "rCy06HY6L_4", "Juntos_Num_S%C3%B3_Ritmo_vlo1jd.wav"),
("We Are One (Ole Ola)", "TGtWWb9emYI", "We_Are_One_Ole_Ola_wpb1x1.wav"),
("Bate no Peito (clipe oficial)", "lXupnGzEMZs", "Bate_no_Peito_clipe_oficial_ciz7tz.wav"),
("Essa É a Nossa Copa", "w2zvtviqAU0", "Essa_%C3%89_a_Nossa_Copa_usvx7g.wav");
