use Ritualia;

INSERT INTO songs (title, artist, source_id, explication_source, description) VALUES
("Dias de Luta, Dias de Glória", "Charlie Brown Jr.", "6eEOegzrwJg", "explication_audios/dias_de_luta_dias_de_gloria_charlie_brown_jr.wav", 'Quando a banda parecia ter acabado após a saída de quase todos os integrantes em 2005, surgiu essa faixa como uma resposta de sobrevivência. Ela não é só um rock marcante: virou o maior hino brasileiro sobre transformar os tombos da vida em combustível. É o recado perfeito para quando tudo parece dar errado, lembrando que a vitória só existe para quem tem coragem de encarar a correria.'),
("Tempo Perdido", "Legião Urbana", "LqmRIG1plVU", "explication_audios/tempo_perdido_legiao_urbana.wav", 'Aquele riff de violão inconfundível que todo mundo tenta arranhar no instrumento nasceu para ser um antídoto contra o medo de crescer. Criada no meio da efervescência dos anos 80, a faixa virou um verdadeiro escudo protetor: um lembrete direto de que ter incertezas faz parte da vida e que a juventude não precisa carregar o peso do mundo nas costas.'),
("Por Você", "Barão Vermelho", "JhwJ7_h0i-M", "explication_audios/por_voce_barao_vermelho.wav", 'A prova de que a declaração de amor perfeita não precisa ser séria ou certinha está nessa lista de promessas absurdas. Escrever sobre beber o mar de canudinho ou atravessar o planeta a pé transformou o clichê romântico em uma brincadeira genial, provando que amar de verdade é ter a coragem de parecer ridículo com um sorriso no rosto.'),
("Andar com Fé", "Gilberto Gil", "kyy4SqIw-EY", "explication_audios/andar_com_fe_gilberto_gil.wav", 'Mais do que uma oração, esse clássico dos anos 80 transformou a espiritualidade em puro ritmo e movimento. Em vez de pregar dogmas, a mensagem é um abraço aberto: ter fé não é ficar esperando um milagre sentado, mas sim ter a coragem de colocar o pé na estrada e seguir em frente, não importa o tamanho do desafio.'),
("Cálice", "Chico Buarque & Gilberto Gil", "9y2xB90A0CY", "explication_audios/calice_chico_buarque_gilberto_gil.wav", 'Substituir o som de uma ordem de silêncio pelo som de uma taça foi o truque de mestre mais desafiador da nossa música. Criada em meio à censura da ditadura, essa letra usou uma sonoridade idêntica — o eco de "cale-se" disfarçado de "cálice" — para cantar o que era proibido falar, mostrando como a inteligência da arte consegue furar qualquer bloqueio e dar voz à liberdade.'),
("Oceano", "Djavan", "P-lxOj0XpEE", "explication_audios/oceano_djavan.wav", 'Gravada com a participação especial de uma lenda do flamenco espanhol que estava de passagem pelo Brasil, essa faixa ganhou um solo de violão inesquecível de Paco de Lucía. A mistura genial do ritmo espanhol com a nossa poesia transformou o sentimento de vulnerabilidade em pura potência, mostrando como a arte ganha força quando cruza qualquer fronteira.'),
("Amanhã Sei Lá", "Marcos & Belutti", "tu5bpM3CcUw", "explication_audios/amanha_sei_la_marcos_belutti.wav", 'Viver com medo do amanhã só faz a gente esquecer de aproveitar o agora. Essa faixa transforma o sertanejo em uma verdadeira lição de "carpe diem": uma provocação leve para desligar a ansiedade sobre o futuro e focar totalmente no momento presente. Afinal, o hoje é tudo o que temos — o resto, a gente descobre pelo caminho.'),
("Romaria", "Renato Teixeira", "OYCS6SJtHvI", "explication_audios/romaria_renato_teixeira.wav", 'Um caipira na cidade grande transformou a saudade de casa no maior retrato da fé popular brasileira. Ao levar a modinha de viola para o topo da MPB, essa composição deu um banho de orgulho na cultura do interior, provando que a vida simples na roça carrega uma poesia potente sobre esperança, resistência e as raízes do nosso povo.'),
("Evidências", "Chitãozinho & Xororó", "ePjtnSPFWK8", "explication_audios/evidencias_chitaozinho_xororo.wav", 'Nenhum karaokê ou festa brasileira está imune ao poder desse verdadeiro hino nacional informal. Nascida no início dos anos 90, a faixa quebrou as barreiras entre o sertanejo e o pop, virando um fenômeno cultural capaz de unir todas as gerações no mesmo grito. Ela prova como uma grande melodia pode ultrapassar o tempo e virar um patrimônio afetivo de todo o país.'),
('Apesar de Você', 'Chico Buarque', 'bGAJlOwUgHY', 'explication_audios/apesar_de_voce.wav', 'Um censor liberou a letra achando que era só briga de casal ciumento. Erro fatal: em três meses, o compacto vendeu mais de cem mil cópias e virou grito coletivo contra a ditadura militar. Quando o regime entendeu a ironia, mandou recolher e destruir as cópias — mas não conseguiu apagar o hino que o Brasil já tinha decorado.'),
('Alegria, Alegria', 'Caetano Veloso', 'he_ghOAXbSM', 'explication_audios/alegria_alegria.wav', 'Guitarra elétrica era coisa de ianque, proibida por puristas da MPB. Aos 25 anos, o baiano subiu ao palco do Festival da Record em 1967 acompanhado de uma banda de rock argentina e foi recebido a vaias. Terminou aplaudido, ficou só em quarto lugar, mas plantou a semente da Tropicália — e mudou os rumos da música brasileira para sempre.'),
('Aquele Abraço', 'Gilberto Gil', 'zFGMLQ3q15c', 'explication_audios/aquele_abraco.wav', 'Preso pela ditadura em 1969 e prestes a partir para o exílio em Londres, o autor saiu da cadeia justo na Quarta-feira de Cinzas, encontrou o Rio ainda enfeitado de carnaval e transformou a dor em despedida generosa. O título vem da gozação dos soldados que o vigiavam. Virou hit nacional antes mesmo de ele ouvir a versão final gravada.'),
('O Bêbado e a Equilibrista', 'Elis Regina', 'oCcREJdgRXM', 'explication_audios/o_bebado_e_a_equilibrista.wav', "Nasceu de um luto: João Bosco recebeu a notícia da morte de Charlie Chaplin no Natal de 1977 e quis homenageá-lo. Aldir Blanc transformou aquele Carlitos melancólico em porta-voz dos exilados políticos, pedindo a volta do 'irmão do Henfil'. Na voz de Elis, virou hino informal da anistia — dizem que ela chorou ao ouvir a letra pela primeira vez, sabendo o que aquilo representava."),
('Coração de Estudante', 'Milton Nascimento', 'pI734oE7iUw', 'explication_audios/coracao_de_estudante.wav', 'Nasceu como tema instrumental para um documentário sobre João Goulart, sem uma palavra de letra. Foi Milton quem, num gesto raro em sua carreira, decidiu escrever versos inspirados em Edson Luís, estudante morto pela ditadura em 1968 — e batizou a canção com o nome de uma flor mineira. Virou trilha sonora emocional das Diretas Já, tocada até no luto por Tancredo Neves.'),
('Blowin’ in the Wind', 'Bob Dylan', 'MMFj8uDubsE', 'explication_audios/blowin_in_the_wind.wav', 'Dez minutos foi o tempo que levou para nascer, num café de Nova York em 1962 — a melodia vinha emprestada de um antigo spiritual cantado por ex-escravizados fugitivos. Na estreia ao vivo, o autor mal conseguia ler sua própria letra rabiscada às pressas e improvisou versos na hora. Virou hino da era dos direitos civis sem nunca dar respostas, só perguntas que ecoam até hoje.'),
('We Shall Overcome', 'Joan Baez', 'nM39QUiAsoM', 'explication_audios/we_shall_overcome.wav', 'Nem Baez a escreveu — a canção nasceu de hinos gospel do início do século 20 e ganhou forma final nas mãos de ativistas como Pete Seeger e Zilphia Horton. Ela apenas emprestou a voz, mas foi essa voz, cantada diante de 250 mil pessoas na Marcha sobre Washington em 1963, que gravou a música na memória do mundo como o hino definitivo dos direitos civis.'),
('The Sound of Silence', 'Simon & Garfunkel', 'NAEppFUWLfc', 'explication_audios/the_sound_of_silence.wav', 'Trancado no banheiro, luzes apagadas, torneira aberta só pelo som da água ecoando nos azulejos — foi assim, aos 21 anos, que o autor encontrou o clima perfeito para compor. Seis meses de trabalho até que, num único dia de fevereiro de 1964, a letra brotou inteira. O silêncio virou metáfora para a incapacidade humana de realmente se ouvir.'),
('Feeling Good', 'Nina Simone', 'oHRNrgDIJfo', 'explication_audios/feeling_good.wav', "Não nasceu para ser hino de liberdade: era só um número de um musical britânico esquecido de 1964, cantado por um personagem sem nome, apenas chamado 'O Negro', depois de vencer um jogo trapaceado contra dois brancos. Um ano depois, a voz certa a resgatou do esquecimento e a transformou em manifesto de emancipação — puro triunfo emocional sobre a dor."),
('Imagine', 'John Lennon', 'VOgFZfRVaww', 'explication_audios/imagine.wav', 'Por quase 50 anos, o mundo cantou uma letra que pertencia a duas pessoas, mas só creditava uma. A estrutura poética veio direto do livro de poemas conceituais da esposa do autor, publicado em 1964 — inclusive um verso sobre imaginar nuvens pingando. Só em 2017, décadas depois, ela finalmente recebeu o crédito de coautoria que ele mesmo já tinha admitido ser dela por direito.'),
('Epitáfio', 'Titãs', 'cvznde5nc_s', 'explication_audios/epitafio.wav', 'Foi composta antes, mas parece profecia: um dia antes de entrar em estúdio para gravar o disco, o guitarrista fundador da banda morreu atropelado em São Paulo. Curiosamente, a canção quase ficou de fora — recebeu apenas 4 votos dos 7 integrantes na votação interna. Sérgio Britto, que a escreveu, foi um dos poucos que acreditou nela. Virou o maior hit do álbum.'),
('Sociedade Alternativa', 'Raul Seixas', 'CfgYcLBP9lI', 'explication_audios/sociedade_alternativa.wav', "Não era só uma canção, era um manifesto — parceria de Raul com o futuro escritor best-seller Paulo Coelho, mergulhados juntos nos rituais ocultistas de Aleister Crowley em 1974. O verso 'faze o que tu queres' vem direto da Lei de Thelema. A ideia levou a Polícia Federal a apreender material considerado subversivo e Raul foi preso, obrigado a delatar quem fazia parte do movimento antes de ser exilado."),
('Alagados', 'Os Paralamas do Sucesso', 'r6esToXGQJM', 'explication_audios/alagados.wav', "O nome não é figura de linguagem: Alagados é um bairro real de palafitas em Salvador, erguido sobre um manguezal. A letra costura essa realidade a Trenchtown, na Jamaica, e à Maré, no Rio, unindo três periferias do mundo numa só canção. Curiosamente, quando Herbert mostrou a letra aos parceiros, achou que soava 'samba demais' — a banda a reinventou com influências africanas e convidou Gilberto Gil para gravar junto."),
('Pro Dia Nascer Feliz', 'Barão Vermelho', 'sQzT4VObtZs', 'explication_audios/pro_dia_nascer_feliz.wav', "Ninguém acreditou nela até a campainha tocar de madrugada: Ney Matogrosso apareceu na casa de Cazuza anunciando 'vou gravar Pro Dia Nascer Feliz — tá na hora de ganhar dinheiro'. A banda, apelidada de 'grupo maldito' por não emplacar sucesso, decolou graças à versão dele. A letra celebra a boemia carioca, a vida ao contrário do relógio: dormir quando o mundo acorda."),
('Hey Jude', 'The Beatles', 'A_MjCqQoLLA', 'explication_audios/hey_jude.wav', "Ela nasceu como 'Hey Jules', cantarolada num carro a caminho da casa de um garoto de 5 anos cujos pais estavam se separando. O autor foi visitá-lo para dizer que tudo ficaria bem. Décadas depois, esse mesmo garoto, hoje adulto, admitiu ter uma relação de 'amor e ódio' com o hino mundial escrito só para ele — um lembrete constante da família que se desfazia."),
('We Will Rock You', 'Queen', '-tJYN-eG1zk', 'explication_audios/we_will_rock_you.wav', 'Aquele bumbum-tibum icônico não é bateria — é a própria banda pisando e batendo palmas sobre pranchas de madeira em corredores de estúdio, gravado umas 15 vezes e sobreposto até virar uma multidão inteira. A ideia nasceu num show de 1977, quando os fãs, em vez de aplaudir, cantaram em uníssono um hino de futebol — e Brian May quis devolver esse poder coletivo diretamente ao público.'),
('Sunday Bloody Sunday', 'U2', 'Iqlzoz_jH3c', 'explication_audios/sunday_bloody_sunday.wav', 'Os tambores marciais não são só efeito estético — ecoam de propósito a violência de 1972, quando tropas britânicas atiraram por 25 minutos contra manifestantes desarmados em Derry, matando 14 pessoas. Onze anos depois, a banda irlandesa gravou a batida usando a escadaria do próprio estúdio como caixa de eco, recusando-se a tomar partido entre católicos e protestantes: um grito contra a violência, não um hino de guerra.'),
('Another Brick in the Wall', 'Pink Floyd', 'qs35t2xFqdU', 'explication_audios/another_brick_in_the_wall.wav', 'O produtor Bob Ezrin gostou tanto da faixa que agiu pelas costas do próprio autor da música, que não queria expandi-la além de um minuto. Recrutou 23 alunos de uma escola vizinha ao estúdio, sem revelar a letra rebelde antes dos ensaios, e trocou o trabalho por ingressos e um disco. Só décadas depois, graças a uma mudança na lei britânica, aquelas crianças — já adultas — finalmente receberam seus direitos autorais.'),
('Smells Like Teen Spirit', 'Nirvana', 'hTWKbfoikeg', 'explication_audios/smells_like_teen_spirit.wav', "O maior hino da geração grunge nasceu de uma piada bêbada que ninguém entendeu direito: uma amiga rabiscou 'Kurt cheira a Teen Spirit' na parede do apartamento dele, referência irônica a um desodorante usado pela ex-namorada dele. O autor achou que era um slogan revolucionário e só descobriu a verdade — que era zoeira sobre cheiro de suor — meses depois de o disco já ter estourado no mundo inteiro."),
('As Rosas Não Falam', 'Cartola', '5j3QjEk-6c0', 'explication_audios/as_rosas_nao_falam.wav', "Uma resposta desinteressada virou um dos maiores versos do samba: a esposa do compositor, encantada com as roseiras do jardim, perguntou por que tinham desabrochado tantas flores. Ele só soltou 'não sei, as rosas não falam' — e a frase não saiu mais da cabeça dele. Pegou o violão e a canção nasceu quase pronta em minutos, três dias antes de completar 67 anos: seu presente de aniversário para si mesmo."),
('Com Que Roupa?', 'Noel Rosa', 'CUo6DLq_F0E', 'explication_audios/com_que_roupa.wav', "Um erro de leitura quase virou hino nacional errado: quando o compositor cantarolou o samba para um violoncelista transcrever, os primeiros compassos soaram tão parecidos com o Hino Nacional Brasileiro que precisaram ser corrigidos na partitura. Aos 19 anos, o autor transformava gíria carioca — 'com que roupa' significava 'com que dinheiro' — em retrato irônico da Crise de 29, um 'Brasil de tanga, pobre e maltrapilho', como ele mesmo confessou a um tio."),
('O Mar Serenou', 'Clara Nunes', 'drGewMyo00A', 'explication_audios/o_mar_serenou.wav', 'Escrita por Candeia, um dos grandes nomes históricos da Portela, a canção transforma uma sambista qualquer numa sereia capaz de acalmar o mar e ofuscar a lua com sua presença. Lançada em 1975, ajudou a consolidar a virada de carreira mais improvável da música brasileira: uma cantora que começou como intérprete de boleros e, incentivada por Ataulfo Alves, se tornou a primeira mulher a vender mais de cem mil discos de samba no país.'),
('Canta, Canta Minha Gente', 'Martinho da Vila', 'X4Tp_TmjHRs', 'explication_audios/canta_canta_minha_gente.wav', "Repare no verso escondido no fim: 'só não dá pra cantar mesmo é vendo o sol nascer quadrado' — referência velada a quem está preso, enxergando o amanhecer emoldurado pela grade da cela. Lançada em 1974, a canção é quase um dicionário cantado do universo do samba, citando de samba de breque a partido alto, um catálogo de ritmos que celebra a resistência através do canto, mesmo nos tempos mais duros."),
('Foi um Rio que Passou em Minha Vida', 'Paulinho da Viola', 'DFBBy0RY8p0', 'explication_audios/foi_um_rio_que_passou_em_minha_vida.wav', "A faísca criativa veio da vitrine de uma livraria: caminhando pela Rua México, no Rio, em 1969, o compositor viu por acaso o título de um livro — 'Por Onde Andou Meu Coração' — e não conseguiu esquecer a frase. Chegou em casa, pegou o violão e transformou aquilo numa declaração de amor à Portela. Curiosamente, a canção nasceu como forma de se redimir com sua escola, depois de ter feito um hino de sucesso para a rival Mangueira."),
('Sodade', 'Cesária Évora', 'ku_WZoTtT8Q', 'explication_audios/sodade.wav', 'A canção guarda uma dor dupla: a letra fala da separação forçada dos cabo-verdianos enviados para trabalhar nas roças de São Tomé, fugindo da fome nas ilhas. Décadas depois, a própria autoria virou disputa judicial — só em 2006 a Justiça reconheceu Armando Zeferino Soares, que a compôs nos anos 1950, como o verdadeiro autor, corrigindo um crédito que por anos foi atribuído a outra dupla.'),
('Pata Pata', 'Miriam Makeba', 'JBJVVhn7iuo', 'explication_audios/pata_pata.wav', "A própria autora a considerava 'insignificante' — só uma canção de dança sobre baladas de fim de semana. Mas gravada por uma mulher exilada da África do Sul por lutar contra o apartheid, cantada em xhosa nos bares clandestinos de Joanesburgo, virou símbolo internacional de resistência. Regime que lhe cassou a cidadania nunca conseguiu calar o que sua voz representava fora do país."),
('Chan Chan', 'Buena Vista Social Club', 'tGbRZ73NvlY', 'explication_audios/chan_chan.wav', "O compositor jurava que nunca escreveu a música — apenas a sonhou. Acordou com quatro notas ecoando na cabeça e uma história de infância sobre um casal camponês construindo uma casa. O refrão 'de Alto Cedro, voy para Marcané' traça um mapa real do leste cubano, e o verso final, sobre recolher areia, esconde uma insinuação sexual disfarçada de simplicidade rural — puro talento de trovador."),
('Clandestino', 'Manu Chao', 'TyA-oz7lSrc', 'explication_audios/clandestino.wav', "Foi gravada com um laptop simples, apelidado pelo próprio autor de 'Estúdio Clandestino', enquanto ele viajava sozinho pela América Latina, África e Europa após o fim de sua banda anterior. A errância pessoal virou retrato universal do imigrante sem papéis — 'fantasma na cidade' —, misturando espanhol, francês, galego e português num só álbum, décadas antes de o tema voltar a dominar os debates políticos europeus."),
('7 Seconds', 'Youssou NDour & Neneh Cherry', 'wqCpjFMvz-k', 'explication_audios/7_seconds.wav', 'Ninguém esperava que uma faixa cantada em três idiomas — wolof, francês e inglês — dominasse as paradas europeias, mas ficou 16 semanas seguidas no topo na França, recorde da época. O título vem dos primeiros sete segundos de vida de um bebê recém-nascido, tempo em que, segundo Neneh Cherry, ele ainda não tem noção da própria cor de pele — um manifesto sonoro contra o racismo construído a partir da inocência pura.'),
('Festa', 'Ivete Sangalo', 'h2xU3E6kePw', 'explication_audios/festa.wav', "Ela mistura, no mesmo verso, batuque de candomblé com guitarras de rock'n roll — combinação que rendeu polêmica e chegou a ser censurada em uma emissora de TV. Composta por Anderson Cunha e lançada em 2001, a canção virou trilha inesperada do pentacampeonato da Seleção Brasileira em 2002, transformando o gueto, historicamente marginalizado, em símbolo de festa, ancestralidade afro-brasileira e orgulho coletivo."),
('Show das Poderosas', 'Anitta', 'FGViL3CYRwg', 'explication_audios/show_das_poderosas.wav', 'Foi o gesto calculado de uma jovem funkeira decidida a virar estrela pop num Brasil dominado por rock e sertanejo: letra sem palavrão, refrão chiclete, clipe simples e barato — mas o suficiente para torná-la a primeira brasileira a passar de 100 milhões de visualizações no YouTube. Lançada em 2013, catapultou a autora de MC de bailes funk a fenômeno nacional quase da noite para o dia.'),
('Ainda Bem', 'Marisa Monte', 'Pmt01TGsGGA', 'explication_audios/ainda_bem.wav', "A faixa não nasceu para a autora cantar: foi escrita originalmente para a diva italiana Mina, que a gravou em seu próprio disco. Só depois, a compositora resolveu guardá-la para si — e o coração 'aposentado, sem nenhuma ilusão' da letra virou retrato de quem já tinha desistido do amor. Lançada em 2011, tornou-se a canção mais executada da carreira dela, segundo o Ecad."),
('Quando Você Passa (Turu Turu)', 'Sandy & Junior', '1Ornig3pdMU', 'explication_audios/quando_voce_passa_turu_turu.wav', "Aquele 'turu turu' pegajoso não é invenção brasileira: nasceu na Itália, criada por três compositores italianos como 'Turuturu', e ganhou versão nacional das mãos de um executivo da gravadora. A onomatopeia representa o coração disparado de quem está apaixonado — e funcionou tão bem que, em 2002, virou uma das músicas mais tocadas do Brasil, cravada na memória de toda uma geração de adolescentes."),
('Heal the World', 'Michael Jackson', 'BWf-eARnf6U', 'explication_audios/heal_the_world.wav', "Nasceu com outro nome, 'Feed the World', e foi composta subindo em uma árvore mesmo — o autor dizia tê-la criado sentado em sua 'árvore de dar', no rancho Neverland. O clipe é um dos poucos da carreira dele sem sua própria imagem, focado só em crianças de países em crise. Anos depois, confessou publicamente que essa era a canção da qual mais se orgulhava, e usou o nome dela para batizar sua fundação beneficente."),
('Halo', 'Beyoncé', 'bnVUHWCynig', 'explication_audios/halo.wav', "Nasceu em três horas, com um dos compositores literalmente de muletas: o vocalista da OneRepublic havia acabado de romper o tendão de Aquiles e mal podia se mexer quando o parceiro insistiu para irem ao estúdio mesmo assim. Inspirados por uma canção folk de Ray LaMontagne, batizaram a faixa 'Halo' ao ouvir os acordes 'angelicais' no piano — e ela quase foi cantada por outra artista, que a recusou por conflito de agenda."),
('Viva La Vida', 'Coldplay', 'dvgZkm1xWPE', 'explication_audios/viva_la_vida.wav', "O título nunca é dito na letra — vem de um quadro pintado por Frida Kahlo apenas oito dias antes de morrer, doente e acamada, mas ainda assim escrevendo 'viva a vida' sobre melancias vibrantes. Chris Martin viu a obra na Casa Azul, no México, ficou tomado pela coragem daquele gesto e batizou não só a música, mas todo o álbum — mudando também a estética visual da banda do preto e branco melancólico para as cores intensas que a marcam até hoje."),
('Someone Like You', 'Adele', 'hLQl3WQQoQ0', 'explication_audios/someone_like_you.wav', 'O ex-namorado que inspirou a canção estava noivo de outra pessoa poucos meses depois do fim do namoro de 18 anos, um relacionamento que a autora achava que terminaria em casamento. Ela confessou temer, aos quarenta anos, procurá-lo e descobrir que ele construiu a família feliz que ela sonhava — enquanto ela seguia sozinha. Composta ao piano em apenas dois dias com Dan Wilson, virou balada de dor universal com um arranjo propositalmente cru e minimalista.'),
('Shape of You', 'Ed Sheeran', 'JGwWNGJdvx8', 'explication_audios/shape_of_you.wav', "A canção quase nunca teve a voz do próprio autor: foi escrita pensando num dueto de Rihanna com o grupo Rudimental. O detalhe que mudou tudo? Uma referência ao cantor Van Morrison ('put Van the Man on the jukebox') que os compositores acharam meio deslocada para o estilo da cantora caribenha — então decidiram guardá-la para si. Virou a faixa mais tocada da história do Spotify até ser superada anos depois."),
('Bachianas Brasileiras nº 5', 'Heitor Villa||Lobos', 'pUCuEd1tjCg', 'explication_audios/bachianas_brasileiras_no_5.wav', 'Nasceu instrumental para oito violoncelos, sem nenhuma voz humana — até o compositor se apaixonar pela melodia feita pelo primeiro cello e decidir reescrevê-la para soprano. Composta em 1938, ela une Bach e Brasil de um jeito só possível na obra de Villa-Lobos: a letra veio sete anos depois, escrita pelo poeta Manuel Bandeira, quando o segundo movimento finalmente ganhou vida.'),
('Odeon', 'Ernesto Nazareth', 'bEfRtR12Y4k', 'explication_audios/odeon.wav', 'Foi composta em homenagem a um cinema, não a um sentimento: o compositor tocava piano na sala de espera do luxuoso Cine Odeon, no Rio de Janeiro, e tanta gente ia só para ouvi-lo que muitos nem chegavam a assistir ao filme. Foi ali, entre 1909 e 1913, que ele cruzou caminho com nomes como o pianista Arthur Rubinstein. A obra passou décadas discreta até ganhar letra de Vinicius de Moraes na década de 1960 e se tornar seu maior sucesso póstumo.'),
('Garota de Ipanema', 'Tom Jobim & Vinicius de Moraes', 'KJzBxJ8ExRk', 'explication_audios/garota_de_ipanema.wav', "A garota nunca soube que era musa até anos depois: uma adolescente tímida de 17 anos que só entrava naquele bar para comprar cigarro para a mãe virou, sem saber, inspiração da segunda canção mais gravada da história — atrás apenas de 'Yesterday', dos Beatles. Sua identidade real só foi revelada publicamente em 1965, três anos após a composição, quando já estava casada."),
('Ode to Joy', 'Ludwig van Beethoven', '-kcOpyM9cBg', 'explication_audios/ode_to_joy.wav', 'Ele nunca ouviu uma nota do que compôs. Completamente surdo na estreia de 1824, o compositor rejeitou cerca de 200 versões diferentes do tema antes de chegar à melodia final — décadas de obsessão com o poema de Schiller, iniciada ainda aos 23 anos. Na plateia, ao final, precisou que alguém o virasse fisicamente para ver os aplausos que jamais conseguiria escutar. Hoje é o hino oficial da União Europeia.'),
('Eine Kleine Nachtmusik', 'Wolfgang Amadeus Mozart', 'oy2zDJPIgwc', 'explication_audios/eine_kleine_nachtmusik.wav', "Apesar de milhares de cartas, documentos e anotações deixadas pelo compositor, essa serenata quase não deixou rastro — ele mesmo a registrou em seu catálogo pessoal, mas nunca explicou por que a escreveu nem para quem. Pior: o próprio autor listou a obra com cinco movimentos, mas um deles, o primeiro minueto, simplesmente desapareceu e nunca foi encontrado. Composta em 1787, enquanto trabalhava em 'Don Giovanni', segue sendo um pequeno mistério dentro de uma obra genial."),
('What a Wonderful World', 'Louis Armstrong', 'rBrd_3VMC3c', 'explication_audios/what_a_wonderful_world.wav', "Composta em 1967, no auge da tensão racial e da Guerra do Vietnã nos EUA, o presidente da gravadora odiou tanto a canção que se recusou a promovê-la — vendeu apenas mil cópias no lançamento americano. Foi preciso um filme sobre a própria guerra, 'Bom Dia, Vietnã', duas décadas depois, para resgatar do esquecimento essa mensagem de esperança cantada por um homem de 66 anos, com a sabedoria de quem já tinha visto o suficiente do mundo para acreditar nele mesmo assim."),
('Billie Jean', 'Michael Jackson', 'Zi_XLOBDo_Y', 'explication_audios/billie_jean.wav', "Uma fã obcecada mandou uma foto de um suposto filho dele, cobrou pensão em cartas e, no auge da perturbação, chegou a enviar uma arma sugerindo que morressem juntos. O produtor Quincy Jones quase deixou a faixa de fora do álbum, achando o nome arriscado demais — parecido com a tenista Billie Jean King — mas o cantor bateu o pé. Virou o maior hit de 'Thriller', disco mais vendido da história."),
('Like a Prayer', 'Madonna', '79fzeNUqQbQ', 'explication_audios/like_a_prayer.wav', 'Estreou primeiro em comercial de refrigerante — e derrubou o próprio patrocínio dias depois. O clipe, com cruzes em chamas e um beijo em santo negro, provocou boicote global que chegou ao Vaticano: o Papa João Paulo II chegou a proibir a entrada da cantora na Itália. A empresa cancelou o contrato de US$ 5 milhões, mas ela ficou com o dinheiro adiantado e usou para bancar a turnê seguinte. Controvérsia rendeu, ironicamente, o prêmio de vídeo do ano.'),
('Born This Way', 'Lady Gaga', 'wV1FrqwZyKw', 'explication_audios/born_this_way.wav', "A autora chegou a dizer, meio brincando, que nem foi ela quem escreveu a canção: sentiu que era o estilista Alexander McQueen, morto pouco antes, 'manipulando tudo do céu'. Lançada em 2011, evitou de propósito qualquer metáfora poética escondida — ela queria um ataque direto, um hino que citasse explicitamente pessoas trans, gays, negras e de todas as origens, recusando o costume pop de disfarçar mensagens políticas em letras bonitinhas."),
('Levitating', 'Dua Lipa', 'TUVcZfQe-Kw', 'explication_audios/levitating.wav', "Foi a primeira faixa escrita para o álbum, e a autora confessou que, ao compô-la, se imaginava dentro de um filme do Austin Powers — achava que precisava ser divertida, brilhante, mas com letra inteligente. O sucesso na Billboard rendeu 68 semanas seguidas nas paradas, mas também dois processos por plágio, com acusações de que a melodia 'duplicava' composições anteriores — controvérsia amplificada justamente pelo trecho que viralizou no TikTok."),
('Bohemian Rhapsody', 'Queen', 'fJ9rUzIMcZQ', 'explication_audios/bohemian_rhapsody.wav', "Nem os próprios companheiros de banda sabem do que a letra realmente trata: Freddie Mercury jamais explicou o significado, dizendo apenas que 'não sabia' e que revelar qualquer coisa 'estragaria o mistério' que as pessoas construíram. Ele levou a resposta para o túmulo em 1991. Décadas depois, virou a música mais transmitida do século 20 no streaming — pura ousadia de misturar ópera e hard rock numa faixa sem refrão nenhum."),
('Satisfaction', 'The Rolling Stones', 'nrIPxlFzDi0', 'explication_audios/satisfaction.wav', 'O guitarrista literalmente sonhou o riff mais famoso do rock: acordou no meio da noite, gravou meio adormecido num toca-fitas ao lado da cama e voltou a dormir sem lembrar de nada. Na manhã seguinte, achou que estava tocando outra música — até rebobinar a fita e ouvir trinta segundos de genialidade seguidos de quarenta minutos de ronco puro. Ele mesmo duvidava que aquilo daria um single de sucesso.');

INSERT INTO genres (name, path) VALUES
("MPB", "genres/mpb.png"),
("Sertanejo", "genres/sertanejo.png"),
("Rock", "genres/rock.png"),
("Tropicalismo", "genres/tropicalismo.png"),
("Folk", "genres/folk.png"),
("Folk Rock", "genres/folk_rock.png"),
("Jazz", "genres/jazz.png"),
("Pop Rock", "genres/pop_rock.png"),
("Rock Nacional", "genres/rock_nacional.png"),
("Rock Progressivo", "genres/rock_progressivo.png"),
("Grunge", "genres/grunge.png"),
("Samba", "genres/samba.png"),
("Morna", "genres/morna.png"),
("Afropop", "genres/afropop.png"),
("Son Cubano", "genres/son_cubano.png"),
("World Music", "genres/world_music.png"),
("Axé", "genres/axe.png"),
("Funk Pop", "genres/funk_pop.png"),
("Pop", "genres/pop.png"),
("Música Clássica", "genres/musica_classica.png"),
("Choro", "genres/choro.png"),
("Bossa Nova", "genres/bossa_nova.png");

INSERT INTO emotions (name) VALUES
("Esperança"),
("Reflexão"),
("Saudade"),
("Liberdade"),
("Otimismo"),
("Melancolia"),
("Unidade"),
("Introspecção"),
("Empoderamento"),
("Paz"),
("Rebeldia"),
("Indignação"),
("Euforia"),
("Acolhimento"),
("Empolgação"),
("Tensão"),
("Revolta"),
("Raiva"),
("Ironia"),
("Devoção"),
("Alegria"),
("Nostalgia"),
("Animação"),
("Inquietude"),
("Empatia"),
("Serenidade"),
("Romantismo"),
("Compaixão"),
("Paixão"),
("Triunfo"),
("Tristeza"),
("Sensualidade"),
("Elegância"),
("Leveza"),
("Júbilo"),
("Gratidão"),
("Êxtase"),
("Orgulho"),
("Drama"),
("Frustração");

INSERT INTO songs_genres (song_id, genre_id) VALUES
(38, 16),
(41, 1),
(22, 8),
(11, 4),
(7, 2),
(4, 1),
(27, 3),
(10, 1),
(12, 12),
(29, 12),
(48, 21),
(54, 20),
(15, 5),
(58, 10),
(56, 20),
(5, 1),
(32, 12),
(36, 15),
(37, 17),
(30, 22),
(14, 1),
(1, 9),
(52, 21),
(20, 9),
(9, 2),
(18, 7),
(39, 18),
(33, 12),
(50, 22),
(44, 20),
(43, 20),
(24, 20),
(19, 20),
(57, 20),
(55, 20),
(13, 1),
(31, 12),
(6, 1),
(51, 21),
(49, 22),
(35, 14),
(3, 9),
(23, 9),
(42, 20),
(8, 2),
(59, 3),
(47, 20),
(40, 19),
(28, 11),
(21, 9),
(34, 13),
(46, 20),
(26, 3),
(2, 9),
(17, 6),
(45, 20),
(16, 5),
(25, 3),
(53, 7);

INSERT INTO songs_emotions (song_id, emotion_id) VALUES
(1, 5),
(2, 2),
(3, 27),
(4, 5),
(5, 12),
(6, 29),
(7, 34),
(8, 20),
(9, 39),
(10, 1),
(11, 4),
(12, 36),
(13, 1),
(14, 7),
(15, 2),
(16, 7),
(17, 8),
(18, 9),
(19, 10),
(20, 2),
(21, 11),
(22, 12),
(23, 15),
(24, 14),
(25, 30),
(26, 17),
(27, 11),
(28, 18),
(29, 6),
(30, 19),
(31, 26),
(32, 21),
(33, 38),
(34, 3),
(35, 23),
(36, 22),
(37, 25),
(38, 28),
(39, 13),
(40, 9),
(41, 36),
(42, 29),
(43, 28),
(44, 20),
(45, 39),
(46, 31),
(47, 32),
(48, 33),
(49, 33),
(50, 34),
(51, 35),
(52, 34),
(53, 36),
(54, 16),
(55, 37),
(56, 9),
(57, 23),
(58, 39),
(59, 40);


INSERT INTO national_teams(name, anthem_source_id, explication_source, path) VALUES
("brasil", "Z7pFwsX6UVc", "Brasil_nsuay7.wav", "copa_flags/brasil.png"),
("canada", "RidIw0OXs9U", "Canada_sbu0lv.wav", "copa_flags/canada.png"),
("colômbia", "yPSL78YDyZY", "Colombia_ysfnsi.wav", "copa_flags/colombia.png"),
("Espanha", "BsWFAEytD24", "Espanha_rg4xxk.wav", "copa_flags/espanha.png"),
("franca", "YLi5A7BiBVk", "Franca_cstqjd.wav", "copa_flags/franca.png"),
("Inglaterra", "xianOAFljbs", "Inglaterra_ntug23.wav", "copa_flags/inglaterra.png"),
("Japão", "tkXDCs8qX8Y", "Japao_rxyuwe.wav", "copa_flags/japao.png"),
("mexico", "oZkTymsI7eI", "M%C3%A9xico_sw1kiv.wav", "copa_flags/mexico.png"),
("portugal", "DdOEpfypWQA", "Portugal_nmuuhx.wav", "copa_flags/portugal.png"),
("usa", "LroNerBwIV4", "EUA_supfbt.wav", "copa_flags/usa.png"),
("argentina", "2zJ8UsfLa9I", "Argentina_zyowxx.wav", "copa_flags/argentina.png"),
("alemanha", "-k07t4WsXtU", "Alemanha_za09q8.wav", "copa_flags/alemanha.png"),
("holanda", "S1J1St_rU90", "Holanda_c6orvm.wav", "copa_flags/holanda.png");

INSERT INTO brazilian_songs(name, source_id, explication_source) VALUES
("A Taça do Mundo É Nossa", "hJAriHOh1Jg", "A_Ta%C3%A7a_do_Mundo_%C3%89_Nossa_pznbtz.wav"),
("Frevo do Bi", "6z1jZ0oq7mo", "Frevo_do_Bi_gnmx74.wav"),
("Pra Frente Brasil", "LbxtNtGlZxE", "Para_a_Frente_Brasil_mgzbhb.wav"),
("Voa Canarinho Voa", "FSelnob-HIs", "Voa_Canarinho_Voa_rw8ia1.wav"),
("Coração Verde e Amarelo", "vghnSY7IdJg", "Cora%C3%A7%C3%A3o_Verde_e_Amarelo_ryc65o.wav"),
("La La La (Brasil 2014)", "-befR4wHsjQ", "La_La_La_Brasil_2014_ttzie9.wav"),
("Mostra tua força", "VasURheNUOM", "Mostra_tua_for%C3%A7a_pcct0p.wav"),
("Hino do Penta", "SS14L3soacs", "Hino_do_Penta_utngee.wav"),
("País do Futebol", "801gN8_X39E", "Pa%C3%ADs_do_Futebol_m966ox.wav"),
("A Escola de Feola", "MELfSGXA9Ds", "Escola_de_Feola_dprgvv.wav"),
("Waka waka", "pRpeEdMmmQ0", "Waka_waka_ok7qg7.wav"),
("Você chegou", "0NXEDQqILUE", "Voc%C3%AA_chegou_b0had0.wav"),
("Juntos Num Só Ritmo", "rCy06HY6L_4", "Juntos_Num_S%C3%B3_Ritmo_vlo1jd.wav"),
("We Are One (Ole Ola)", "TGtWWb9emYI", "We_Are_One_Ole_Ola_wpb1x1.wav"),
("Bate no Peito (clipe oficial)", "lXupnGzEMZs", "Bate_no_Peito_clipe_oficial_ciz7tz.wav"),
("Essa É a Nossa Copa", "w2zvtviqAU0", "Essa_%C3%89_a_Nossa_Copa_usvx7g.wav");
